services:
  {{ name }}:
    build:
      context: ../..
      dockerfile: {{ location }}/{{ name }}/Dockerfile
    container_name: {{ name }}_web
    ports:
      - "{{ port }}:{{ port }}"
    networks:
      - graphql
    restart: unless-stopped

networks:
  graphql:
