apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
stringData:
  REDIS_PASSWORD: {{ .Values.password | quote }}
