apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "redis.labels" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
