apiVersion: apps/v1
kind: Deployment
metadata:
  name: server2-graphql
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: server2-graphql
  template:
    metadata:
      labels:
        app: server2-graphql
    spec:
      containers:
        - name: server2-graphql
          image: server2-graphql:latest
          envFrom:
            - configMapRef:
                name: server2-graphql-graphql-env
            - configMapRef:
                name: server2-graphql-meilisearch-env
          ports:
            - containerPort: 4002
            - containerPort: 9000
