apiVersion: v1
kind: ConfigMap
metadata:
  name: server2-graphql-meilisearch-env
  namespace: {{ .Values.namespace }}
data:
  MEILISEARCH_HOST: http://meilisearch.infra.svc.cluster.local:7700
  MEILISEARCH_API_KEY: meilimasterkey
