version: v2

clean: true

plugins:
  - local: protoc-gen-ts_proto
    out: ../../packages/api/src/generated/demo1/proto/
    opt:
      - outputServices=grpc-js
      - esModuleInterop=true
      - useOptionals=messages
      - stringEnums=true
      - outputTypeRegistry=true

inputs:
  - directory: ./src/schema/proto/
