namespace: infra

prometheus:
  image: prom/prometheus:v3.1.0
  persistence:
    size: 5Gi

loki:
  image: grafana/loki:3.3.2
  persistence:
    size: 5Gi

tempo:
  image: grafana/tempo:2.6.1
  persistence:
    size: 5Gi

grafana:
  image: grafana/grafana-oss:11.4.0
  adminUser: admin
  adminPassword: admin
  persistence:
    size: 1Gi

otelCollector:
  image: otel/opentelemetry-collector-contrib:0.116.1
