extend schema @link(url: "https://specs.apollo.dev/federation/v2.14", import: [])

type AuthTokens {
  accessToken: String!
  refreshToken: String
  idToken: String
  tokenType: String!
  expiresIn: Int!
}

type SignUpResult {
  id: ID!
  username: String!
  email: String!
}

input SignUpInput {
  username: String!
  email: String!
  password: String!
  name: String
}

type Mutation {
  signIn(username: String!, password: String!): AuthTokens!
  signUp(input: SignUpInput!): SignUpResult!
  signOut(refreshToken: String!): Boolean!
}
