include:
  - ./services/adminer/docker-compose.yml
  - ./services/apollo/docker-compose.yml
  - ./services/kafka/docker-compose.yml
  - ./services/redis/docker-compose.yml
  - ./servers/demo1/docker-compose.yml
  - ./servers/demo2/docker-compose.yml
