include:
  - ./services/adminer/docker-compose.yml
  - ./services/apollo/docker-compose.yml
  - ./services/kafka/docker-compose.yml
  - ./services/redis/docker-compose.yml
  - ./servers/test1/docker-compose.yml
  - ./servers/test2/docker-compose.yml
  - ./apps/web1/docker-compose.yml
  - ./frontends/mfe1/docker-compose.yml
