services:
  demo1:
    build:
      context: ../..
      dockerfile: servers/demo1/Dockerfile
    container_name: demo1_server
    ports:
      - "4001:4001"
      - "5001:5001"
    networks:
      - graphql
      - kafka
    restart: unless-stopped

networks:
  graphql:
  kafka:
