apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
stringData:
  MINIO_ROOT_USER: {{ .Values.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.rootPassword | quote }}
