apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "authentik.postgresql.labels" . | nindent 4 }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
