apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.server.labels" . | nindent 4 }}
stringData:
  AUTHENTIK_SECRET_KEY: {{ .Values.secretKey | quote }}
  AUTHENTIK_POSTGRESQL__PASSWORD: {{ .Values.postgresql.password | quote }}
  AUTHENTIK_BOOTSTRAP_PASSWORD: {{ .Values.bootstrap.password | quote }}
  AUTHENTIK_BOOTSTRAP_TOKEN: {{ .Values.bootstrap.token | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
