apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.worker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "authentik.worker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authentik.worker.labels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
        - name: authentik-worker
          image: "{{ .Values.image }}"
          args: ["worker"]
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: authentik-postgresql
            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.postgresql.user | quote }}
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.postgresql.db | quote }}
            - name: AUTHENTIK_REDIS__HOST
              value: authentik-redis
            - name: AUTHENTIK_BOOTSTRAP_EMAIL
              value: {{ .Values.bootstrap.email | quote }}
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_SECRET_KEY
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_POSTGRESQL__PASSWORD
            - name: AUTHENTIK_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_BOOTSTRAP_PASSWORD
            - name: AUTHENTIK_BOOTSTRAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_BOOTSTRAP_TOKEN
          volumeMounts:
            - name: media
              mountPath: /media
            - name: certs
              mountPath: /certs
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
        - name: certs
          persistentVolumeClaim:
            claimName: authentik-certs
