# yaml-language-server: $schema=../../packages/lib/src/shared/schema/codegen.schema.json
overwrite: true
schema: "./src/schema/graphql/demo1.graphql"
generates:
  "../../packages/api/generated/demo1/graphql/resolvers.ts":
    plugins:
      - typescript
      - typescript-resolvers
    config:
      useIndexSignature: true
      federation: true
      contextType: "./context#Demo1ContextType"
      useTypeImports: true

  "../../packages/api/generated/demo1/graphql/context.ts":
    plugins:
      - add
    config:
      content: |
        export type Demo1ContextType = Record<string, never>;

  "../../packages/api/generated/demo1/graphql/typedefs.graphql":
    plugins:
      - schema-ast
    config:
      includeDirectives: true
  "../../packages/api/generated/demo1/graphql/typedefs.ts":
    plugins:
      - add
    config:
      content: |
        export const typeDefs = await Bun.file(import.meta.dir + "/typedefs.graphql").text();
