include:
  - ./adminer/docker-compose.yml
  - ./apollo/docker-compose.yml
  - ./authentik/docker-compose.yml
  - ./debezium/docker-compose.yml
  - ./kafka/docker-compose.yml
  - ./meilisearch/docker-compose.yml
  - ./minio/docker-compose.yml
  - ./monitoring/docker-compose.yml
  - ./redis/docker-compose.yml
  - ./traefik/docker-compose.yml
  - ./vault/docker-compose.yml
