apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
stringData:
  VAULT_DEV_ROOT_TOKEN_ID: {{ .Values.rootToken | quote }}
