apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sit
ports:
  - port: 8081:30080
    nodeFilters:
      - server:0
  - port: 8444:30443
    nodeFilters:
      - server:0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
