apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "server.fullname" . }}-postgres
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
