apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
