apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      {{- include "loki.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "loki.labels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      # No use of the Kubernetes API from within this pod.
      automountServiceAccountToken: false
      containers:
        - name: loki
          image: "{{ .Values.loki.image }}"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              memory: 512Mi
              ephemeral-storage: 512Mi
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - name: http
              containerPort: 3100
            - name: grpc
              containerPort: 9096
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: config
              mountPath: /etc/loki/local-config.yaml
              subPath: local-config.yaml
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.loki.persistence.size }}
