apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tempo.labels" . | nindent 4 }}
  ports:
    - name: http
      port: 3200
      targetPort: http
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
