services:
  # demo3:
  #   build:
  #     context: ../..
  #     dockerfile: servers/demo3/Dockerfile
  #   container_name: demo3_server
  #   ports:
  #     - "4003:4003"
  #     - "5003:5003"
  #   networks:
  #     - graphql
  #     - kafka
  #   restart: unless-stopped
  postgres:
    image: postgres:latest
    ports:
      - 5101:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - demo3_data:/var/lib/postgresql
    networks:
      - adminer

networks:
  graphql:
  kafka:
  adminer:

volumes:
  demo3_data:
