subgraphs:
   demo1:
      # routing_url: http://host.docker.internal:4001
      routing_url: http://demo1:4001
      schema:
         file: ../../../../servers/demo1/src/schemas/graphql/demo1.graphql

   demo2:
      # routing_url: http://host.docker.internal:4002
      routing_url: http://demo2:4002
      schema:
         file: ../../../../servers/demo2/src/schema/graphql/demo2.graphql

   demo3:
      routing_url: http://demo3:4003
      schema:
         file: ../../../../servers/demo3/src/schemas/graphql/demo3.graphql
